"""
Shared constants for Dynatrace security events (VULNERABILITY_FINDING, VULNERABILITY_SCAN).
Used by vul_finding and vul_scan.
"""

EVENT_PROVIDER = "Renovate"
EVENT_TYPE_VULNERABILITY_FINDING = "VULNERABILITY_FINDING"
EVENT_TYPE_VULNERABILITY_SCAN = "VULNERABILITY_SCAN"
OBJECT_TYPE_FOR_VULNERABILITY_FINDING = "CODE_ARTIFACT"
OBJECT_TYPE_FOR_VULNERABILITY_SCAN = "CODE_REPOSITORY"
PRODUCT_VENDOR = "Mend.io"
PRODUCT_NAME = "Renovate Community"
SOFTWARE_COMPONENT_TYPE = "library"
FINDING_TYPE = "DEPENDENCY_VULNERABILITY"
REMEDIATION_STATUS_AVAILABLE = "AVAILABLE"
REMEDIATION_STATUS_NOT_AVAILABLE = "NOT_AVAILABLE"
SEVERITY_MODERATE = "MODERATE"
DT_RISK_LEVEL_MEDIUM = "MEDIUM"
VALIDATION_LIST_DYNATRACE_FIELDS = ["object.id", "object.name"]